*&---------------------------------------------------------------------*
*& Include          ZBRSD0050_S01
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK BLK1 WITH FRAME TITLE TEXT-T01.
  SELECT-OPTIONS: SO_DELI FOR ZTBSD0060-DELIVNUM.
  SELECT-OPTIONS: SO_DONU FOR ZTBSD0060-DONUM.
  SELECT-OPTIONS: SO_SONU FOR ZTBSD0060-SONUM.
  SELECT-OPTIONS: SO_TRAN FOR ZTBSD0060-TRANSPORT.
  SELECT-OPTIONS: SO_EMPI FOR ZTBSD0060-EMPID.
  SELECT-OPTIONS: SO_DDAT FOR ZTBSD0060-DELIVSDAT.
SELECTION-SCREEN END OF BLOCK BLK1.
